name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          excludeTypes: doc

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

      - name: Check if issue exists
        id: check-issue
        uses: peter-evans/check-issue@v2
        with:
          title: RELEASE ${{ github.ref_name }}

      - name: Update Issue
        if: steps.check-issue.outputs.issue_exists == 'true'
        uses: peter-evans/update-issue@v1
        with:
          issue-number: ${{ steps.check-issue.outputs.issue_number }}
          content-filepath: ./CHANGELOG.md

      - name: Create Issue
        if: steps.check-issue.outputs.issue_exists == 'false'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: RELEASE ${{ github.ref_name }}
          content-filepath: ./CHANGELOG.md
          labels: |
            report
            automated issue

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: git checkout -b release/${{ github.ref_name }}
      - run: npm ci
      - run: npx playwright install
      - run: npm run e2e
      - run: npm test
      - run: git push origin release/${{ github.ref_name }}
      - run: npm run build
      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
      - name: Close Issue
        run: gh issue close --comment "Auto-closing issue" "1"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
